repos:
    - repo: builtin
      hooks:
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-json

    - repo: local
      hooks:
          - id: forge-validate
            name: forge validate
            entry: forge validate .
            language: system
            pass_filenames: false
